"""
AgentVerse — Talent Discovery API Routes (Agent 2)
==================================================
API endpoints for running talent discovery, fetching matches, and updating match response status.
"""

import uuid
from typing import List

from fastapi import APIRouter, Depends, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import get_current_client
from app.database.session import get_db
from app.models.client import Client
from app.schemas.project_match import (
    TalentDiscoveryRequest,
    TalentDiscoveryResponse,
    ProjectMatchResponse,
    UpdateMatchStatusRequest,
)
from app.services.talent_matching_service import TalentMatchingService
from app.utils.logger import get_logger

logger = get_logger(__name__)

router = APIRouter(tags=["Talent Discovery Agent (Agent 2)"])


@router.post(
    "/agents/talent-discovery",
    response_model=TalentDiscoveryResponse,
    status_code=status.HTTP_200_OK,
    summary="Run Talent Discovery Agent matching",
    description=(
        "Consumes the AI requirement analysis output generated by Agent 1 and "
        "runs an intelligent rule-based matching engine against the freelancer database. "
        "Returns the Top 3 best matching freelancers and saves notifications into the database."
    ),
)
async def discover_talent(
    request: TalentDiscoveryRequest,
    db: AsyncSession = Depends(get_db),
    current_client: Client = Depends(get_current_client),
) -> TalentDiscoveryResponse:
    """
    Run Talent Discovery Agent for a given project_id.
    """
    service = TalentMatchingService(db=db)
    matches = await service.discover_and_save_matches(project_id=request.project_id)

    return TalentDiscoveryResponse(
        project_id=request.project_id,
        matches=[ProjectMatchResponse.model_validate(m) for m in matches],
        message="Top 3 freelancers matched successfully by the Talent Discovery Agent.",
    )


@router.get(
    "/projects/{project_id}/matches",
    response_model=List[ProjectMatchResponse],
    summary="Get freelancer matches for a project",
    description="Retrieve stored freelancer matches and current invitation statuses for a project.",
)
async def get_project_matches(
    project_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
    current_client: Client = Depends(get_current_client),
) -> List[ProjectMatchResponse]:
    """
    Retrieve matches for project.
    """
    service = TalentMatchingService(db=db)
    matches = await service.get_project_matches(project_id=project_id)
    return [ProjectMatchResponse.model_validate(m) for m in matches]


@router.patch(
    "/projects/matches/{match_id}/status",
    response_model=ProjectMatchResponse,
    summary="Update freelancer match response status",
    description="Simulate freelancer action by updating invitation status to ACCEPTED or DECLINED.",
)
async def update_match_status(
    match_id: uuid.UUID,
    request: UpdateMatchStatusRequest,
    db: AsyncSession = Depends(get_db),
    current_client: Client = Depends(get_current_client),
) -> ProjectMatchResponse:
    """
    Update match status (ACCEPTED or DECLINED).
    """
    service = TalentMatchingService(db=db)
    match_obj = await service.update_match_status(
        match_id=match_id,
        status=request.status,
    )
    return ProjectMatchResponse.model_validate(match_obj)
