// src/components/progress/ClientProgressTracker.tsx
// Agent 6 — Progress Monitoring & Recovery Intelligence Client Component

import React, { useState } from 'react';
import {
  Activity, CheckCircle2, AlertTriangle, Clock, ShieldAlert,
  Download, ExternalLink, FileText, GitBranch, Loader2, Sparkles,
  Trophy, RefreshCw, XCircle, ChevronRight, UserCheck
} from 'lucide-react';
import { useProjectProgress } from '@/hooks/useProjectProgress';

interface ClientProgressTrackerProps {
  projectId: string;
}

export const ClientProgressTracker: React.FC<ClientProgressTrackerProps> = ({ projectId }) => {
  const {
    overview,
    isLoading,
    isUpdating,
    error,
    handleDelayAction,
    acceptSubmission,
  } = useProjectProgress(projectId);

  const [isAccepting, setIsAccepting] = useState(false);

  if (!isLoading && !overview) {
    return null;
  }

  if (isLoading) {
    return <div className="skeleton h-72 rounded-2xl mt-8" />;
  }

  if (!overview) return null;

  const handleAccept = async () => {
    setIsAccepting(true);
    try {
      await acceptSubmission();
    } finally {
      setIsAccepting(false);
    }
  };

  const tasks = overview.tasks || [];
  const sub = overview.submission;
  const report = overview.completion_report;

  return (
    <div className="mt-12 pt-8 border-t border-white/10">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-emerald-500/20 to-teal-500/20 border border-emerald-500/30 flex items-center justify-center shadow-lg shadow-emerald-500/10">
            <Activity size={24} className="text-emerald-400" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-2xl font-extrabold text-white">🤖 Progress Monitoring & Recovery Intelligence</h2>
              <span className="badge-green text-xs font-semibold px-2.5 py-0.5">Agent 6 Active</span>
            </div>
            <p className="text-gray-400 text-sm mt-1 max-w-3xl">
              Real-time AI monitoring of milestone progress, delay grace alerts, recovery intelligence, and submission verification.
            </p>
          </div>
        </div>

        <div className="px-4 py-2.5 rounded-xl bg-emerald-500/15 border border-emerald-500/30 text-emerald-300 text-xs font-bold flex items-center gap-2 self-start md:self-auto shadow-lg shadow-emerald-500/10">
          <CheckCircle2 size={16} className="text-emerald-400" />
          <span>Agent 6 Active • Continuous Monitoring</span>
        </div>
      </div>

      {/* 🎉 PROJECT COMPLETION REPORT BANNER */}
      {report && (
        <div className="p-8 rounded-3xl bg-gradient-to-r from-emerald-950/90 via-teal-950/80 to-purple-950/90 border-2 border-emerald-500/50 shadow-2xl mb-8 relative overflow-hidden animate-fade-in">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 relative z-10">
            <div className="flex items-start gap-5">
              <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400 flex-shrink-0 shadow-xl">
                <Trophy size={36} />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-2xl">🎉</span>
                  <h3 className="text-2xl font-black text-white">Project Successfully Completed!</h3>
                </div>
                <p className="text-emerald-300 text-sm font-semibold mb-4">
                  Official Completion Report generated by AgentVerse Autonomous Platform.
                </p>

                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
                  <div className="p-3 rounded-xl bg-white/10 border border-white/10">
                    <p className="text-gray-400">Total Duration</p>
                    <p className="text-white font-extrabold text-base mt-0.5">{report.total_duration_days} Days</p>
                  </div>
                  <div className="p-3 rounded-xl bg-white/10 border border-white/10">
                    <p className="text-gray-400">Approved Budget</p>
                    <p className="text-emerald-400 font-extrabold text-base mt-0.5">₹{report.approved_budget.toLocaleString()} INR</p>
                  </div>
                  <div className="p-3 rounded-xl bg-white/10 border border-white/10">
                    <p className="text-gray-400">Lead Freelancer</p>
                    <p className="text-purple-300 font-extrabold text-base mt-0.5">{report.freelancer_name}</p>
                  </div>
                  <div className="p-3 rounded-xl bg-white/10 border border-white/10">
                    <p className="text-gray-400">Milestones Completed</p>
                    <p className="text-blue-300 font-extrabold text-base mt-0.5">{report.milestones_completed_count} Milestones</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ⚠️ DELAY DETECTION & AI RECOVERY ALERT */}
      {overview.delay_warning && (
        <div className={`p-6 rounded-2xl border-2 mb-8 shadow-2xl relative overflow-hidden animate-fade-in ${
          overview.is_delay_failed
            ? 'bg-gradient-to-r from-red-950/90 via-amber-950/80 to-dark-950 border-red-500/60'
            : 'bg-gradient-to-r from-amber-950/90 via-yellow-950/70 to-dark-950 border-amber-500/50'
        }`}>
          <div className="flex flex-col md:flex-row md:items-start justify-between gap-6 relative z-10">
            <div className="flex items-start gap-4">
              <div className={`w-14 h-14 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-lg ${
                overview.is_delay_failed
                  ? 'bg-red-500/20 border border-red-500/40 text-red-400'
                  : 'bg-amber-500/20 border border-amber-500/40 text-amber-400'
              }`}>
                <ShieldAlert size={30} />
              </div>
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className={`text-xs font-extrabold px-2.5 py-0.5 rounded-full ${
                    overview.is_delay_failed ? 'badge-red' : 'badge-yellow'
                  }`}>
                    {overview.is_delay_failed ? '⚠ Milestone Failed' : '⚠️ Milestone Overdue'}
                  </span>
                  <h3 className="text-xl font-extrabold text-white">Project Delay Detected</h3>
                </div>
                <p className="text-gray-200 text-sm font-semibold mb-3">
                  {overview.delay_warning}
                </p>

                {/* OpenRouter AI Recovery Summary Box */}
                {overview.ai_recovery_summary && (
                  <div className="p-4 rounded-xl bg-black/40 border border-amber-500/30 text-xs">
                    <p className="text-amber-400 font-bold uppercase tracking-wider mb-1 flex items-center gap-1.5">
                      <Sparkles size={14} />
                      AI Recovery Summary (&lt;= 80 words)
                    </p>
                    <p className="text-gray-300 leading-relaxed font-normal">
                      "{overview.ai_recovery_summary}"
                    </p>
                  </div>
                )}
              </div>
            </div>

            {/* Client Recovery Action Buttons */}
            {overview.is_delay_failed && (
              <div className="flex flex-col sm:flex-row gap-3 flex-shrink-0">
                <button
                  onClick={() => handleDelayAction('CONTINUE')}
                  disabled={isUpdating}
                  className="btn-primary bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-extrabold text-xs py-3 px-5 rounded-xl flex items-center justify-center gap-2 shadow-lg"
                >
                  {isUpdating ? (
                    <Loader2 size={16} className="animate-spin" />
                  ) : (
                    <>
                      <CheckCircle2 size={16} />
                      <span>Continue Project</span>
                    </>
                  )}
                </button>

                <button
                  onClick={() => handleDelayAction('CANCEL_REASSIGN')}
                  disabled={isUpdating}
                  className="py-3 px-5 rounded-xl text-xs font-bold transition-all flex items-center justify-center gap-2 bg-red-600/30 hover:bg-red-600 hover:text-white text-red-300 border border-red-500/40 shadow-lg"
                >
                  {isUpdating ? (
                    <Loader2 size={16} className="animate-spin" />
                  ) : (
                    <>
                      <XCircle size={16} />
                      <span>Cancel & Reassign Candidate</span>
                    </>
                  )}
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Metrics Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <div className="glass-card p-5 border border-emerald-500/20">
          <p className="text-gray-400 text-xs font-semibold">Overall Progress</p>
          <p className="text-emerald-400 font-black text-3xl mt-1">{overview.overall_progress_percentage}%</p>
          {/* Progress bar */}
          <div className="w-full bg-white/10 rounded-full h-2 mt-3 overflow-hidden">
            <div
              className="bg-gradient-to-r from-emerald-500 via-teal-500 to-blue-500 h-full rounded-full transition-all duration-500"
              style={{ width: `${overview.overall_progress_percentage}%` }}
            />
          </div>
        </div>

        <div className="glass-card p-5 border border-blue-500/20">
          <p className="text-gray-400 text-xs font-semibold">Completed Tasks</p>
          <p className="text-blue-400 font-black text-3xl mt-1">{overview.completed_tasks_count} Tasks</p>
          <p className="text-gray-500 text-[11px] mt-2">Verified deliverables</p>
        </div>

        <div className="glass-card p-5 border border-purple-500/20">
          <p className="text-gray-400 text-xs font-semibold">Current Milestone</p>
          <p className="text-purple-300 font-black text-3xl mt-1">Phase {overview.current_milestone_number}</p>
          <p className="text-gray-500 text-[11px] mt-2">{overview.pending_tasks_count} tasks remaining</p>
        </div>

        <div className="glass-card p-5 border border-amber-500/20">
          <p className="text-gray-400 text-xs font-semibold">Remaining Timeline</p>
          <p className="text-amber-400 font-black text-3xl mt-1">{overview.remaining_days} Days</p>
          <p className="text-gray-500 text-[11px] mt-2">Target completion deadline</p>
        </div>
      </div>

      {/* FINAL SUBMISSION DELIVERABLES & REVIEW CARD (ALWAYS VISIBLE TO CLIENT WHEN SUBMITTED) */}
      {sub && (
        <div className="p-6 rounded-2xl bg-gradient-to-br from-indigo-950/90 via-purple-950/80 to-dark-950 border-2 border-indigo-500/50 shadow-2xl mb-8 animate-fade-in">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-3 flex-1">
              <div className="flex items-center gap-2 mb-1">
                <span className={`text-xs font-extrabold px-3 py-1 rounded-full ${
                  report ? 'badge-green' : 'badge-indigo'
                }`}>
                  {report ? 'DELIVERABLES APPROVED ✓' : 'DELIVERABLES SUBMITTED'}
                </span>
                <h3 className="text-xl font-extrabold text-white">
                  {report ? 'Submitted Final Deliverables & Source Code' : 'Final Project Submission Ready for Review'}
                </h3>
              </div>
              <p className="text-indigo-200 text-xs leading-relaxed">
                {report
                  ? 'All code repositories, ZIP archives, and live deployment links submitted by freelancer:'
                  : 'The freelancer has uploaded the complete project code archive, GitHub repository, and live deployment links for client review.'}
              </p>

              <div className="flex flex-wrap items-center gap-3 pt-2">
                {sub.github_url ? (
                  <a
                    href={sub.github_url}
                    target="_blank"
                    rel="noreferrer"
                    className="py-2.5 px-4 rounded-xl bg-purple-600/30 hover:bg-purple-600/50 text-purple-200 text-xs font-extrabold flex items-center gap-2 border border-purple-500/40 shadow-lg transition-all"
                  >
                    <GitBranch size={16} className="text-purple-400" />
                    <span>GitHub Repo: {sub.github_url}</span>
                    <ExternalLink size={12} />
                  </a>
                ) : (
                  <span className="text-gray-500 text-xs italic">No GitHub URL provided</span>
                )}

                {sub.zip_file_path ? (() => {
                  const zipPath = sub.zip_file_path;
                  return (
                    <a
                      href={
                        zipPath.startsWith('http') || zipPath.startsWith('blob:')
                          ? zipPath
                          : '#'
                      }
                      onClick={(e) => {
                        if (!zipPath.startsWith('http') && !zipPath.startsWith('blob:')) {
                          e.preventDefault();
                          const element = document.createElement('a');
                          const file = new Blob([`AgentVerse Project Deliverable Archive: ${zipPath}\nProject Source Code & Deliverables.`], { type: 'application/zip' });
                          element.href = URL.createObjectURL(file);
                          element.download = zipPath.endsWith('.zip') ? zipPath : `${zipPath}.zip`;
                          document.body.appendChild(element);
                          element.click();
                          document.body.removeChild(element);
                        }
                      }}
                      className="py-2.5 px-4 rounded-xl bg-emerald-600/30 hover:bg-emerald-600/50 text-emerald-200 text-xs font-extrabold flex items-center gap-2 border border-emerald-500/40 shadow-lg transition-all cursor-pointer group"
                      title="Click to download/view project ZIP archive"
                    >
                      <Download size={16} className="text-emerald-400 group-hover:scale-110 transition-transform" />
                      <span>Download Project ZIP: <strong>{zipPath}</strong></span>
                      <ExternalLink size={12} className="text-emerald-300 opacity-70 group-hover:opacity-100" />
                    </a>
                  );
                })() : (
                  <span className="text-gray-500 text-xs italic">No ZIP file path provided</span>
                )}

                {sub.deployment_url && (
                  <a
                    href={sub.deployment_url}
                    target="_blank"
                    rel="noreferrer"
                    className="py-2.5 px-4 rounded-xl bg-blue-500/20 hover:bg-blue-500/30 text-blue-300 text-xs font-extrabold flex items-center gap-2 border border-blue-500/40 shadow-lg transition-all"
                  >
                    <ExternalLink size={16} className="text-blue-400" />
                    <span>Live App: {sub.deployment_url}</span>
                    <ExternalLink size={12} />
                  </a>
                )}

                {sub.documentation_path && (
                  <span className="py-2.5 px-4 rounded-xl bg-amber-500/20 text-amber-300 text-xs font-extrabold flex items-center gap-2 border border-amber-500/40 shadow-lg">
                    <FileText size={16} className="text-amber-400" />
                    <span>Docs PDF: {sub.documentation_path}</span>
                  </span>
                )}
              </div>
            </div>

            {!report && (
              <button
                onClick={handleAccept}
                disabled={isAccepting}
                className="btn-primary bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-extrabold text-sm py-4 px-6 rounded-2xl flex items-center justify-center gap-2 shadow-xl shadow-emerald-500/20 flex-shrink-0"
              >
                {isAccepting ? (
                  <Loader2 size={18} className="animate-spin" />
                ) : (
                  <>
                    <CheckCircle2 size={18} />
                    <span>Accept & Complete Project</span>
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      )}

      {/* Tasks Progress Breakdown List */}
      <div className="glass-card p-6 border border-white/10">
        <h3 className="text-white font-bold text-lg mb-4 flex items-center gap-2">
          <span>Milestone Tasks Execution Status</span>
          <span className="badge-purple text-xs font-semibold px-2 py-0.5">{tasks.length} Tasks</span>
        </h3>

        <div className="space-y-3">
          {tasks.map((task) => (
            <div
              key={task.id}
              className={`p-4 rounded-xl border transition-all flex flex-col md:flex-row md:items-center justify-between gap-4 ${
                task.status === 'COMPLETED'
                  ? 'bg-emerald-950/20 border-emerald-500/30'
                  : task.status === 'IN_PROGRESS'
                  ? 'bg-blue-950/20 border-blue-500/30'
                  : task.status === 'OVERDUE' || task.status === 'FAILED'
                  ? 'bg-red-950/20 border-red-500/30'
                  : 'bg-white/5 border-white/5'
              }`}
            >
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="badge-gray text-[10px] font-bold px-2 py-0.5">
                    Phase {task.milestone_number}
                  </span>
                  <h4 className="text-white font-bold text-sm">{task.task_name}</h4>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                    task.status === 'COMPLETED'
                      ? 'badge-green'
                      : task.status === 'IN_PROGRESS'
                      ? 'badge-blue'
                      : task.status === 'OVERDUE'
                      ? 'badge-yellow'
                      : task.status === 'FAILED'
                      ? 'badge-red'
                      : 'badge-gray'
                  }`}>
                    {task.status}
                  </span>
                </div>
                {task.description && (
                  <p className="text-gray-400 text-xs mb-1">{task.description}</p>
                )}
                {task.remarks && (
                  <p className="text-purple-300 text-xs font-mono bg-purple-950/30 p-2 rounded-lg border border-purple-500/20 mt-2">
                    {task.remarks}
                  </p>
                )}
              </div>

              <div className="flex items-center gap-3 text-xs text-gray-400 flex-shrink-0">
                <span className="flex items-center gap-1">
                  <Clock size={12} className="text-amber-400" />
                  Due: {new Date(task.planned_end_date).toLocaleDateString()}
                </span>
                {task.actual_completion_date && (
                  <span className="text-emerald-400 font-semibold flex items-center gap-1">
                    ✓ Completed {new Date(task.actual_completion_date).toLocaleDateString()}
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
